### create users include profiles
POST http://localhost:3000/v1/users
Content-Type: application/json

{
    "name": "abiyyi",
    "email": "abiyyisaja@gmail.com",
    "password": "biyyiz",
    "identity_type": "KTP",
    "identity_number": "3578012412020005",
    "address": "Jl. Tuman No.03"

}

### get all users
GET http://localhost:3000/v1/users

### get users by id
GET http://localhost:3000/v1/users/4

### update users includ profiles by id
PUT http://localhost:3000/v1/users/5
Content-Type: application/json

{
    "name": "michael",
    "email": "abcde@gmail.com",
    "password": "123456",
    "identity_type": "SIM",
    "identity_number": "3578012412031231",
    "address": "Jl. Langit Malam No.2 AB"

}

### delete users by id
DELETE http://localhost:3000/v1/users/7

### create bank_accounts
POST http://localhost:3000/v1/accounts
Content-Type: application/json

{
    "bank_name": "BRI",
    "bank_account_number": "123947611117193",
    "balance": 2000000,
    "user_id": 4
}

### get all accounts
GET http://localhost:3000/v1/accounts

### get account by id
GET http://localhost:3000/v1/accounts/4

### update accounts by id
PUT http://localhost:3000/v1/accounts/4
Content-Type: application/json

{
    "bank_name": "Mandiri",
    "bank_account_number": "76518395874444",
    "balance": 1000000

}

### delete accounts by id
DELETE http://localhost:3000/v1/accounts/

### create transactions
POST http://localhost:3000/v1/transactions
Content-Type: application/json

{
    "amount": 150000,
    "sourceAccount": 1,
    "destinationAccount": 3
}

### get all transactions
GET http://localhost:3000/v1/transactions

### get transactions by id
GET http://localhost:3000/v1/transactions/1

### delete transactions by id
DELETE http://localhost:3000/v1/transactions/7