POST http://localhost:3000/v1/users
Content-Type: application/json

{
    "name": "Kibow",
    "email": "kibow@gmail.com",
    "password": "kibowole",
    "identity_type": "KTP",
    "identity_number": "3578012412030001",
    "address": "Jl. Los Angles No.3 B"

}

###
GET http://localhost:3000/v1/users

###
GET http://localhost:3000/v1/users/4


